In [1]:
import torch
import pandas as pd
import numpy as np
from sklearn.svm import SVR
from sklearn.svm import LinearSVR
from sklearn.metrics import mean_absolute_error


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [13]:
df1 = pd.read_csv('/content/drive/MyDrive/IIIT-K_Internship/Mobility-prediction/data/vanet-trace-creteil-20130924-0700-0900.csv', sep=';')
df2 = pd.read_csv('/content/drive/MyDrive/IIIT-K_Internship/Mobility-prediction/data/vanet-trace-creteil-20130924-1700-1900.csv',sep=';')

In [ ]:
df1.head()

timestep_time  vehicle_slope  ... vehicle_speed                vehicle_id
0            0.0            0.0  ...           0.0        BusFlowEastWest0.0
1            0.0            0.0  ...           0.0      BusFlowNorthSouth0.0
2            0.0            0.0  ...           0.0      BusFlowSouthNorth0.0
3            0.0            0.0  ...           0.0        BusFlowWestEast0.0
4            0.0            0.0  ...           0.0  VehicleFlowEastToNorth.0

[5 rows x 10 columns]

In [14]:
df1=df1[df1['vehicle_id']=='BusFlowNorthSouth0.0']

In [15]:
cols = ['vehicle_slope', 'vehicle_lane', 'vehicle_angle', 'vehicle_type', 'vehicle_pos', 'vehicle_speed','vehicle_id', 'vehicle_y']
df1.drop(cols, axis=1, inplace=True)

In [16]:
df2 = df1.copy()
df2 = df2.reset_index()

In [17]:
from sklearn.model_selection import train_test_split

X_train = df2['timestep_time'][:int(len(df2)*0.8)]
y_train = df2['vehicle_x'][:int(len(df2)*0.8)]
X_test = df2['timestep_time'][int(len(df2)*0.8):]
y_test = df2['vehicle_x'][int(len(df2)*0.8):]
#X_train, X_test, y_train, y_test = train_test_split(df2['timestep_time'], df2['vehicle_x'], test_size=0.2, random_state=0)

In [ ]:
#X_train.reset_index()
y_train.head()

0    1270.66
1    1269.56
2    1266.50
3    1264.45
4    1259.56
Name: vehicle_x, dtype: float64

In [33]:
time_st = X_train.to_numpy()
vehicle_x = y_train.to_numpy()

#Convert to 1d Vector
time_st = np.reshape(time_st, (len(time_st), 1))
vehicle_x = np.reshape(vehicle_x, (len(vehicle_x), 1))

svr_rbf = LinearSVR(C= 1e3)#SVR(kernel='linear')##
svr_rbf.fit(time_st, vehicle_x.ravel())


'''
svr_rbf = SVR(kernel= 'linear', C= 1e3, gamma= 0.1)
svr_rbf.fit(time_st, vehicle_x)

plt.figure(figsize = (12,6))
plt.plot(time_st, prices, color= 'black', label= 'Data')
plt.plot(org_dates, svr_rbf.predict(dates), color= 'red', label= 'RBF model') 
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.show()
'''

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


"\nsvr_rbf = SVR(kernel= 'linear', C= 1e3, gamma= 0.1)\nsvr_rbf.fit(time_st, vehicle_x)\n\nplt.figure(figsize = (12,6))\nplt.plot(time_st, prices, color= 'black', label= 'Data')\nplt.plot(org_dates, svr_rbf.predict(dates), color= 'red', label= 'RBF model') \nplt.xlabel('Date')\nplt.ylabel('Price')\nplt.legend()\nplt.show()\n"

In [ ]:
time_st = X_train.to_numpy()
vehicle_x = y_train.to_numpy()

#Convert to 1d Vector
time_st = np.reshape(time_st, (len(time_st), 1))
vehicle_x = np.reshape(vehicle_x, (len(vehicle_x), 1))

svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(time_st, vehicle_x.ravel())



SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
time_st = X_train.to_numpy()
vehicle_x = y_train.to_numpy()

#Convert to 1d Vector
time_st = np.reshape(time_st, (len(time_st), 1))
vehicle_x = np.reshape(vehicle_x, (len(vehicle_x), 1))

svr_rbf = SVR(kernel='poly')
svr_rbf.fit(time_st, vehicle_x.ravel())


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
time_st = X_train.to_numpy()
vehicle_x = y_train.to_numpy()

#Convert to 1d Vector
time_st = np.reshape(time_st, (len(time_st), 1))
vehicle_x = np.reshape(vehicle_x, (len(vehicle_x), 1))

svr_rbf = SVR(kernel='sigmoid')
svr_rbf.fit(time_st, vehicle_x.ravel())


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='sigmoid', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [34]:
time_st_test = X_test.to_numpy()
time_st_test = np.reshape(time_st_test, (len(time_st_test), 1))


In [35]:
pred = svr_rbf.predict(time_st_test)

In [36]:
pred

array([1215.44977246, 1215.17287199, 1214.89597151, 1214.61907104,
       1214.34217056, 1214.06527009, 1213.78836961, 1213.51146914,
       1213.23456866, 1212.95766819, 1212.68076771, 1212.40386724,
       1212.12696676, 1211.85006629, 1211.57316581, 1211.29626534,
       1211.01936487, 1210.74246439, 1210.46556392, 1210.18866344,
       1209.91176297, 1209.63486249, 1209.35796202, 1209.08106154,
       1208.80416107, 1208.52726059, 1208.25036012, 1207.97345964,
       1207.69655917, 1207.41965869, 1207.14275822, 1206.86585774,
       1206.58895727, 1206.31205679, 1206.03515632, 1205.75825584])

In [37]:
y_expected = y_test.to_numpy()
#y_expected = np.reshape(y_expected, (len(y_expected), 1))


In [38]:
y_expected

array([1197.7 , 1197.7 , 1197.7 , 1197.7 , 1197.7 , 1197.7 , 1197.7 ,
       1197.7 , 1197.7 , 1197.7 , 1197.7 , 1197.7 , 1197.7 , 1197.7 ,
       1197.17, 1196.13, 1196.3 , 1198.78, 1199.85, 1199.85, 1199.85,
       1199.85, 1199.85, 1199.85, 1199.92, 1201.69, 1205.59, 1204.5 ,
       1200.  , 1196.41, 1192.98, 1189.16, 1184.89, 1180.81, 1177.71,
       1174.24])

In [39]:
from sklearn.metrics import classification_report

from sklearn.metrics import mean_squared_error

print(mean_squared_error(y_expected, pred))

242.35300403114172


In [ ]:
# Linear - 288.8957681723039 , poly - 480.11893520942056 , rbf - 323.1114741252943 , sigmoid - 2025.4807775667691

In [40]:
print("Root mean square error - RMSE ") 
print(mean_squared_error(y_expected, pred, squared=False))

Root mean square error - RMSE 
15.567691030822193


In [41]:
print("Mean absolute error - MAE")
print(mean_absolute_error(y_expected, pred))

Mean absolute error - MAE
14.404569708649092


In [42]:
from sklearn.utils.validation import check_consistent_length, check_array

def mean_absolute_percentage_error(y_true, y_pred,
                                   sample_weight=None,
                                   multioutput='uniform_average'):
    """Mean absolute percentage error regression loss.
    Note here that we do not represent the output as a percentage in range
    [0, 100]. Instead, we represent it in range [0, 1/eps]. Read more in the
    :ref:`User Guide <mean_absolute_percentage_error>`.
    .. versionadded:: 0.24
    Parameters
    ----------
    y_true : array-like of shape (n_samples,) or (n_samples, n_outputs)
        Ground truth (correct) target values.
    y_pred : array-like of shape (n_samples,) or (n_samples, n_outputs)
        Estimated target values.
    sample_weight : array-like of shape (n_samples,), default=None
        Sample weights.
    multioutput : {'raw_values', 'uniform_average'} or array-like
        Defines aggregating of multiple output values.
        Array-like value defines weights used to average errors.
        If input is list then the shape must be (n_outputs,).
        'raw_values' :
            Returns a full set of errors in case of multioutput input.
        'uniform_average' :
            Errors of all outputs are averaged with uniform weight.
    Returns
    -------
    loss : float or ndarray of floats in the range [0, 1/eps]
        If multioutput is 'raw_values', then mean absolute percentage error
        is returned for each output separately.
        If multioutput is 'uniform_average' or an ndarray of weights, then the
        weighted average of all output errors is returned.
        MAPE output is non-negative floating point. The best value is 0.0.
        But note the fact that bad predictions can lead to arbitarily large
        MAPE values, especially if some y_true values are very close to zero.
        Note that we return a large value instead of `inf` when y_true is zero.
    Examples
    --------
    >>> from sklearn.metrics import mean_absolute_percentage_error
    >>> y_true = [3, -0.5, 2, 7]
    >>> y_pred = [2.5, 0.0, 2, 8]
    >>> mean_absolute_percentage_error(y_true, y_pred)
    0.3273...
    >>> y_true = [[0.5, 1], [-1, 1], [7, -6]]
    >>> y_pred = [[0, 2], [-1, 2], [8, -5]]
    >>> mean_absolute_percentage_error(y_true, y_pred)
    0.5515...
    >>> mean_absolute_percentage_error(y_true, y_pred, multioutput=[0.3, 0.7])
    0.6198...
    """
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
        y_true, y_pred, multioutput)
    check_consistent_length(y_true, y_pred, sample_weight)
    epsilon = np.finfo(np.float64).eps
    mape = np.abs(y_pred - y_true) / np.maximum(np.abs(y_true), epsilon)
    output_errors = np.average(mape,
                               weights=sample_weight, axis=0)
    if isinstance(multioutput, str):
        if multioutput == 'raw_values':
            return output_errors
        elif multioutput == 'uniform_average':
            # pass None as weights to np.average: uniform mean
            multioutput = None

    return np.average(output_errors, weights=multioutput)

def _check_reg_targets(y_true, y_pred, multioutput, dtype="numeric"):
    """Check that y_true and y_pred belong to the same regression task.
    Parameters
    ----------
    y_true : array-like
    y_pred : array-like
    multioutput : array-like or string in ['raw_values', uniform_average',
        'variance_weighted'] or None
        None is accepted due to backward compatibility of r2_score().
    Returns
    -------
    type_true : one of {'continuous', continuous-multioutput'}
        The type of the true target data, as output by
        'utils.multiclass.type_of_target'.
    y_true : array-like of shape (n_samples, n_outputs)
        Ground truth (correct) target values.
    y_pred : array-like of shape (n_samples, n_outputs)
        Estimated target values.
    multioutput : array-like of shape (n_outputs) or string in ['raw_values',
        uniform_average', 'variance_weighted'] or None
        Custom output weights if ``multioutput`` is array-like or
        just the corresponding argument if ``multioutput`` is a
        correct keyword.
    dtype : str or list, default="numeric"
        the dtype argument passed to check_array.
    """
    check_consistent_length(y_true, y_pred)
    y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)

    if y_true.ndim == 1:
        y_true = y_true.reshape((-1, 1))

    if y_pred.ndim == 1:
        y_pred = y_pred.reshape((-1, 1))

    if y_true.shape[1] != y_pred.shape[1]:
        raise ValueError("y_true and y_pred have different number of output "
                         "({0}!={1})".format(y_true.shape[1], y_pred.shape[1]))

    n_outputs = y_true.shape[1]
    allowed_multioutput_str = ('raw_values', 'uniform_average',
                               'variance_weighted')
    if isinstance(multioutput, str):
        if multioutput not in allowed_multioutput_str:
            raise ValueError("Allowed 'multioutput' string values are {}. "
                             "You provided multioutput={!r}".format(
                                 allowed_multioutput_str,
                                 multioutput))
    elif multioutput is not None:
        multioutput = check_array(multioutput, ensure_2d=False)
        if n_outputs == 1:
            raise ValueError("Custom weights are useful only in "
                             "multi-output cases.")
        elif n_outputs != len(multioutput):
            raise ValueError(("There must be equally many custom weights "
                              "(%d) as outputs (%d).") %
                             (len(multioutput), n_outputs))
    y_type = 'continuous' if n_outputs == 1 else 'continuous-multioutput'

    return y_type, y_true, y_pred, multioutput

In [43]:
print("MAPE")
print(mean_absolute_percentage_error(y_expected, pred))

MAPE
0.012067215575541697


### no need

In [ ]:
svr_rbf.coef_

array([-0.26003695])

In [ ]:
svr_linear = SVR(kernel= 'linear', C= 1e3, gamma= 0.1)

In [ ]:
svr_rbf._get_coef

<bound method BaseLibSVM._get_coef of SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)>

In [ ]:
svr_linear.coef_.set_(svr_rbf._get_coef)

AttributeError: ignored

In [ ]:
svr_rbf = SVR(kernel= 'linear', C= 1e3, gamma= 0.1)


In [ ]:
from sklearn.svm import LinearSVR

svr_linear = LinearSVR(C= 1e3)
svr_rbf = LinearSVR(C= 1e3)


In [ ]:
svr_rbf.raw_coef

AttributeError: ignored

In [ ]:
svr_linear.coef_.set_(svr_rbf._get_coef)

AttributeError: ignored

In [ ]:
svr_linear.coef_

AttributeError: ignored